version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - cluster.name=PlagiarismPOC
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
       - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    ports:
      - 5601:5601